WebServices/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using AuthenticationService;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Models;

namespace WebServices.Controllers
{
    public class AuthController : Controller
    {
        private readonly AuthenticatorService _userAuth;
        

        public AuthController(AuthenticatorService userAuth)
        {
            
            _userAuth = userAuth;
        }

        public IActionResult Login()
        {
            return View();
        }
        public IActionResult Register()
        {
            return View();
        }

        public async Task<IActionResult> Logout()
        {
            var result = await _userAuth.Logout();
            if (result.Status)
            {
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("SomethingWrong", "Home");

        }

        [HttpPost]
        public async Task<IActionResult> Login(string username, string password)
        {
            var response = await _userAuth.Login(username,password);
            
            if (response.Status)
            { 
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("SomethingWrong", "Home");

        }

        [HttpPost]
        public async Task<ActionResult> Register(string name, string password, string email, string roleName)
        {
            var user = new UserAccount
            {
                NormalizedUserName = name,
                UserName = email,
                Email = email,
                Name = name
            };

            var response = await _userAuth.Register(user,password,roleName);
            
            if (response.Status)
            {
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("SomethingWrong", "Home");

        }
    }
}

WebServices/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AuthenticationService.UserInformation;
using Microsoft.AspNetCore.Mvc;
using Models.Model;
using Models.View_Model;

namespace WebServices.Controllers
{
    public class PostController : Controller
    {
        private readonly PostService.PostService _postService;
        private readonly UserInfoService _userInfoService;

        public PostController(PostService.PostService postService,UserInfoService userInfoService)
        {
            _postService = postService;
            _userInfoService = userInfoService;
        }

        public async Task<IActionResult> Index()
        {
            await AssignViewBag();
            UserInfo userInfo = await GetUserInfoDetailes();
            var posts = await _postService.AllPosts(userInfo);
            ViewBag.Posts = posts;
            return View();
        }

        public async Task<IActionResult> Create()
        {
            await AssignViewBag();
            return View();
        }

        public async Task<IActionResult> MyPosts()
        {
            
            await AssignViewBag();
            var user = await GetUserInfoDetailes();
            List<Post> posts = await _postService.FindPostByUsername(user.user);
            ViewBag.Posts = posts;
            return View();
        }
        
        
        public async Task<IActionResult> Edit(int id)
        {
            await AssignViewBag();
            Post Post = await _postService.FindPostById(id);
            ViewBag.Post = Post;
            return View();
        }

        public async Task<IActionResult> Delete(int id)
        {
            var response = await _postService.DeletePost(id);
            if (response.Status) return RedirectToAction("MyPosts");
            return RedirectToAction("SomethingWrong", "Home");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Post post)
        {
            var response = await _postService.EditPost(post,new Post());
            if (response.Status) return RedirectToAction("MyPosts");
            return RedirectToAction("SomethingWrong","Home");
        }

        

        [HttpPost]
        public async Task<IActionResult> Create(Post post)
        {
            var user = await GetUserInfoDetailes();
            post.user = user.user;
            var response =  await _postService.CreatePost(post);
            if (response.Status)
            {
                return RedirectToAction("MyPosts");
            }

            return RedirectToAction("SomethingWrong", "Home");
        }


        private async Task AssignViewBag()
        {
            var detailes = await GetUserInfoDetailes();
            ViewBag.Name = detailes.user.Name;
            ViewBag.Role = detailes.roleName;
        }

        private async Task<UserInfo> GetUserInfoDetailes()
        {
            return await _userInfoService.GetUserDetailes(User.Identity.Name);
        }
    }
}

WebServices/Views/Shared/NavMenu.cshtml
@{
    ViewData["Title"] = "NavMenu";
}

<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Interview Board App</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
            <ul class="navbar-nav flex-grow-1">
                @if (ViewBag.Role == "giver")
                {
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
@*                     <li class="nav-item"> *@
@*                         <a class="nav-link text-dark" asp-area="" asp-controller="Post" asp-action="Create">Create Job</a> *@
@*                     </li> *@
@* *@
@*                     <div class="nav-item justify-content-end mr-auto"> *@
@*                         <li class="nav-item"> *@
@*                             <a class="nav-link text-dark" asp-area="" asp-controller="Post" asp-action="MyPosts">My Posts</a> *@
@*                         </li> *@
@*                     </div> *@
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Welcome @ViewBag.Name</a>
                    </li>

                    <li class="nav-item justify-content-end">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Logout">Logout</a>
                    </li>

                }
                else if (ViewBag.Role == "")
                {
                    <div class="nav-item justify-content-end mr-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </div>

                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Register">Register</a>
                    </li>
                }
                else
                {
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
@*                     <div class="nav-item justify-content-end mr-auto"> *@
@*                         <li class="nav-item"> *@
@*                             <a class="nav-link text-dark" asp-area="" asp-controller="Post" asp-action="MyInterviews">My Inteviews</a> *@
@*                         </li> *@
@* *@
@*                     </div> *@
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Welcome @ViewBag.Name</a>
                    </li>

                    <li class="nav-item justify-content-end">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Logout">Logout</a>
                    </li>

                }

            </ul>


        </div>
    </div>
</nav>

WebServices/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - JobMarket</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<style>
    textarea {
        width: 100%;
        height: 100px;
        padding: 6px 10px;
        box-sizing: border-box;
        border: 2px solid #ccc;
        border-radius: 4px;
        background-color: #f8f8f8;
        font-size: 16px;
        resize: none;
    }

    div.fixed {
        position: fixed;
        width: 100%;
        bottom: 0px;
        background-color: white;
        padding-left: 100px;
    }

    .card {
        box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
        transition: 0.3s;
        width: 80%;
        margin-top: 20px;
    }

    .chat {
        box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
        transition: 0.3s;
        width: 50%;
        margin-top: 20px;
    }

    .chat-my {
        background-color: #3b5998;
        color: white;
        margin-left: 400px;
    }

    .card:hover {
        box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
    }

    .container {
        padding: 2px 16px 16px;
    }

    .container-chat {
        padding: 2px 6px 6px;
    }


    .grid-container {
        display: grid;
        grid-template-columns: auto;
        padding: 10px;
    }

    .grid-item {
        /* background-color: rgba(255, 255, 255, 0.8); */
        border: 1px solid rgba(0, 0, 0, 0.8);
    }
</style>

<body>

    @RenderBody()

    @* <footer class="border-top footer text-muted"> *@
    @*     <div class="container"> *@
    @*         &copy; 2020 - InterviewBoard - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> *@
    @*     </div> *@
    @* </footer> *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>